# Generated by Django 3.1.6 on 2021-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('income', models.IntegerField()),
                ('family', models.IntegerField()),
                ('ccavg', models.FloatField()),
                ('education', models.IntegerField()),
                ('mortgage', models.IntegerField()),
                ('personal_loan', models.IntegerField()),
                ('sec_account', models.IntegerField()),
                ('cd_account', models.IntegerField()),
                ('online', models.IntegerField()),
                ('credit_card', models.IntegerField()),
            ],
        ),
    ]
